esphome:
  name: jura-coolcontrol
  friendly_name: jura-coolcontrol

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

external_components:
 - source:
      type: git
      url: https://github.com/tiaanv/jura
   components: [jura_coolcontrol]   

# Enable logging
logger:
  baud_rate: 0
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "<yourkey>"

ota:
  - platform: esphome
    password: "<yourotasecret>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jura-Coolcontrol"
    password: "<yourpassword>"

captive_portal:


uart:
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 9600
  id: uart_bus

jura_coolcontrol:
  id: jura_cool
  uart_id: uart_bus
  level:
    name: "Jura Coolcontrol Level"
  temperature:
    name: "Jura Coolcontrol Temperature"

    