esphome:
  name: jura-f7
  friendly_name: "Jura F7"

esp8266:
  board: d1_mini

external_components:
 - source:
      type: git
      url: https://github.com/tiaanv/jura
   components: [jura]

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jura F7 Fallback"
    password: "fallbackpassword"

captive_portal:

uart:
  tx_pin: D1
  rx_pin: D2
  baud_rate: 9600
  id: uart_bus

# Jura Coffee Machine Component
jura:
  id: jura_coffee
  uart_id: uart_bus
  model: F7

# Control Buttons
button:
  - platform: template
    name: 'Turn On Coffee Machine'
    icon: "mdi:coffee-maker"
    id: jura_turn_on
    on_press:
      - lambda: |-
          auto result = id(jura_coffee).cmd2jura("AN:01");

  - platform: template
    name: 'Turn Off Coffee Machine'
    icon: "mdi:coffee-maker-outline"
    id: jura_turn_off
    on_press:
      - lambda: |-
          auto result = id(jura_coffee).cmd2jura("AN:02");

  - platform: template
    name: 'Make Hot Water'
    icon: "mdi:cup-water"
    id: jura_make_hot_water
    on_press:
      - lambda: |-
          auto result = id(jura_coffee).cmd2jura("FA:06");

  - platform: template
    name: 'Make Espresso'
    icon: "mdi:coffee"
    id: jura_make_espresso
    on_press:
      - lambda: |-
          auto result = id(jura_coffee).cmd2jura("FA:04");

  - platform: template
    name: 'Make Ristretto'
    icon: "mdi:coffee"
    id: jura_make_ristretto
    on_press:
      - lambda: |-
          auto result = id(jura_coffee).cmd2jura("FA:05");

  - platform: template
    name: 'Make Coffee'
    icon: "mdi:coffee"
    id: jura_make_coffee
    on_press:
      - lambda: |-
          auto result = id(jura_coffee).cmd2jura("FA:09");

  - platform: template
    name: 'Make Cappuccino'
    icon: "mdi:coffee"
    id: jura_make_cappuccino
    on_press:
      - lambda: |-
          auto result = id(jura_coffee).cmd2jura("FA:07");

  - platform: restart
    name: Restart
